#!/usr/bin/env python3
import argparse
import asyncio
import sys
import traceback

from _pushbank.daemon import PushBank

def main():
    parser = argparse.ArgumentParser(
        description='PushBank CLI application.')
    args = parser.parse_args()

    pushbank = PushBank()

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(pushbank.execute(loop))
    except KeyboardInterrupt:
        pass
    except:
        print("""
        오류가 발생했습니다. 다음 오류를 복사해서
        https://github.com/ssut/PushBank2/issues 에 제보해주시면
        오류를 수정하는데 많은 도움이 됩니다:
        """.strip().replace('    ', ''))
        traceback.print_exc()
    return 0

if __name__ == '__main__':
    sys.exit(main())
